# Generated by Django 2.1.1 on 2018-11-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20181115_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(choices=[(True, '管理员'), (False, '普通用户')], default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
