# Generated by Django 2.1.1 on 2018-12-07 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20181129_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='IP地址')),
                ('type', models.CharField(choices=[('Physical', '物理机'), ('Virtual', '虚拟机'), ('Container', '容器'), ('Disk', '硬盘')], default='Virtual', max_length=128, verbose_name='平台')),
                ('serial_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='序列号')),
                ('asset_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='资产号')),
                ('position', models.CharField(blank=True, max_length=128, null=True, verbose_name='位置')),
                ('idle', models.BooleanField(default=True, verbose_name='空闲')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='assets.ProjectProfile', verbose_name='项目组'),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='宿主', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='assets.HostProfile', verbose_name='宿主'),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ProjectProfile', verbose_name='项目组'),
        ),
    ]
