# Generated by Django 2.1.1 on 2018-12-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20181207_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostprofile',
            name='type',
            field=models.CharField(choices=[('Physical', '物理机'), ('Virtual', '虚拟机'), ('Container', '容器'), ('Disk', '硬盘')], default='Virtual', max_length=128, verbose_name='类型'),
        ),
    ]
